---

- block:

  - name: create group on server {{ server.name }}
    tags: server
    delegate_to: &server '{{ server.name }}'
    group:
      name: &name '{{ user.name }}'
      gid: &uid '{{ user.uid }}'

  - name: create group on client {{ client.name }}
    tags: client
    delegate_to: &client '{{ client.name }}'
    group:
      name: *name
      gid: *uid

  - name: create user {{ user.name }} on server {{ server.name }}
    tags: server
    delegate_to: *server
    user:
      name: *name
      group: *name
      uid: *uid
      comment: &comment '{{ user.comment }}'
      home: '{{ server.home|default(server.path) }}'
      shell: '{{ server.shell|default(options.shell) }}'
      createhome: False

  - name: create user {{ user.name }} on client {{ client.name }}
    tags: client
    delegate_to: *client
    user:
      name: *name
      group: *name
      uid: *uid
      comment: *comment
      home: '{{ client.home|default(client.path) }}'
      shell: '{{ client.shell|default(options.shell) }}'
      createhome: False
      update_password: on_create

  when: user.exists is not defined

- name: create pre-dir on server {{ server.name }}
  tags: server
  delegate_to: *server
  file:
    path: |-
      {{ server.path.split('/')[:-1]|join('/') }}
    state: directory

- name: create dir on server {{ server.name }}
  tags: server
  delegate_to: *server
  file:
    path: '{{ server.path }}'
    state: directory
    owner: *name
    group: *name
    mode: &mode '{{ mode }}'

- name: create pre-dir on client {{ client.name }}
  tags: client
  delegate_to: *client
  file:
    path: |-
      {{ client.path.split('/')[:-1]|join('/') }}
    state: directory

- name: create dir on client {{ client.name }}
  tags: client
  delegate_to: *client
  file:
    path: '{{ client.path }}'
    state: directory
    owner: *name
    group: *name
    mode: *mode

- name: install NFS on server
  tags: server
  delegate_to: *server
  apt: { name: nfs-kernel-server }

- name: install NFS on client {{ client.name }}
  tags: client
  delegate_to: *client
  apt: { name: nfs-common }

- name: export dir for client on server {{ server.name }}
  tags: server
  delegate_to: *server
  notify: restart nfs-kernel-server
  lineinfile:
    dest: /etc/exports
    insertafter: EOF
    line: |-
      {{ server.path }} {{ client.node }}{{ server.export|default(options.export) }}

- name: mount dir from server on client {{ client.name }}
  tags: client
  delegate_to: *client
  lineinfile:
    dest: /etc/fstab
    insertafter: EOF
    line: |-
      {{ server.node }}:{{ server.path }} {{ client.path }} nfs {{ options.mount }}
